services:
  - type: web
    name: voisins-connect-backend
    env: rust
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/hello_world_backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_osO3xDfwiIm2@ep-dry-union-aym1o38g-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: MONGODB_URL
        value: mongodb+srv://helloworld:helloworld@cluster0.o2z1nqe.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: super_secret_jwt_key_change_in_production_12345
      - key: PORT
        value: "3001"
      - key: S3_BUCKET
        value: dummy
